# Site settings
name: Marius Cetateanu
email: cetatzeanum+contact@gmail.com
#canonical_url: https://edwinexemplar.com
keywords: "Software Engineer, C++, Python, Golang, Java, Machine Learning, Deep Learning, SIMD, TDD, Agile"
skills: "Senior Software Engineer in Brussels, Belgium"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/mariuscetateanu/
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c
  primary-rgb: "19, 150, 125"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1


# Build settings
markdown: kramdown
permalink: pretty
